version: '3.7'
services:
  fixel-be-container:
    image: 03nmt/fixel-be-image:v1.0.3
    container_name: fixel-be-container
    command: sh -c "npm install && npm run start:dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - backend
    environment:
      PORT: ${PORT}
  postgres-container:
    image: postgres:14.1
    container_name: postgres-container
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"  # Sử dụng biến môi trường POSTGRES_PORT hoặc mặc định 5432
    volumes:
      - fixel-postgres-database:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"

networks:
  backend:
    name: fixel-app-network

volumes:
  fixel-postgres-database:
